connection:
  port: /dev/ttyUSB0
  baudrate: 10400
  timeout: 1.0

# Default table to stream with 'live' command.
active_table: 0x11

tables:
  0x11:
    name: "Live Telemetry"
    expected_length: 22
    parameters:
      # rdata: [71, 11, 05, DD, 17, 00, 42, 6B, 6D, 51, 74, 4E, FF, FF, 85, 00, 02, 52, 93, 27, 15, E7]

      rpm:
        offset: 2
        length: 2
        endian: big
        formula: "x"
        unit: "rpm"

      tps:
        offset: 4
        length: 1
        formula: "x * 0.39215"
        unit: "%"

      map:
        offset: 6
        length: 1
        formula: "x"
        unit: "kPa"

      iat:
        offset: 7
        length: 1
        formula: "x - 40"
        unit: "°C"

      ect:
        offset: 14
        length: 1
        formula: "x - 40"
        unit: "°C"

      o2:
        offset: 10
        length: 1
        formula: "x"
        unit: "raw"

      iacv:
        offset: 16
        length: 1
        formula: "x"
        unit: "steps"

      injector:
        offset: 17
        length: 1
        formula: "x"
        unit: "raw"

      battery:
        offset: 18
        length: 1
        formula: "x / 10.0"
        unit: "V"

      speed:
        offset: 15
        length: 1
        formula: "x"
        unit: "km/h"
